spring.application.name=backend

# Configuración de Servidor
server.port=8081

# Configuración de Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/resisync_db
spring.datasource.username=resisync_user
spring.datasource.password=resisync_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Token configuration
jwt.secret=8f2c69d8a3b547f2ec08101a05afc12b8f2c69d8a3b547f2ec08101a05afc12b8f2c69d8a3b547f2ec08101a05afc12b
jwt.expiration=86400000
