spring.application.name=backend

# Configuración de Servidor
server.port=5000

# Configuración de Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://zentari-db.cc9wwa24a2kq.us-east-1.rds.amazonaws.com:5432/zentari_db
spring.datasource.username=admzentari
spring.datasource.password=0u883Y3oupRhVjftxh9l
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Token configuration
jwt.secret=8f2c69d8a3b547f2ec08101a05afc12b8f2c69d8a3b547f2ec08101a05afc12b8f2c69d8a3b547f2ec08101a05afc12b
jwt.expiration=86400000
